### ISSUE TITLE
Name violates GNOME HIG

### ISSUE THREAD

**Issue by Commenter25** [azymohliad/watchmate#33]
The [GNOME Human Interface Guidelines](https://developer.gnome.org/hig/guidelines/app-naming.html) states to not use non-standard punctuation or whitespace, such as SuperWriter.

**Comment by azymohliad** [comment]
Yeah, you're right. It's good that you brought it up, because I'm not sure how to properly fix it, so a discussion would be really helpful here.

Initially I ignored this point in the HIG because I liked the idea of catchy made-up words for app names, and I didn't think it's very important to follow it for a small indie app. Embarrassingly, I didn't know "watchmate" is already a word with its own meaning, and I somehow failed to google it. I thought it would be a really snappy way of saying "watch's mate" as a single word.

So not only it violates the GNOME HIG, but it's a flawed name in general. And it seems that any way of fixing the HIG without changing the name completely ("Watch Mate", "Watchmate") would only emphasize those flaws. But I'm also not sure if changing a bad name completely is worth the confusion such change may cause.

What do people think? How misleading and/or dumb the current name is (especially to native English speakers)? How would you propose to fix it (both for the GNOME HIG and in general)?

**Comment by TheKrafter** [comment]
While I don't think the current name is 'dumb' (as a native English speaker) I do think an HIG compliant name would be apt. 

As for a new name, I like the HIG's suggestion of naming things after older, analog versions of something. Maybe we could do something with a "Watchmaker" or derive the name from somewhere in the process of creating/repairing/upkeeping mechanical clocks?

**Comment by azymohliad** [comment]
Thanks for the input @TheKrafter, it is really helpful! For now I'm leaning towards keeping the old name then (just to avoid the confusion), and fix it for the HIG as "Watchmate". But I also don't want to make a new release without bringing functional improvements, so I'll leave it open for more opinions until then. I like "Watchmaker" and mechanical clocks direction if we decide to change it after all.

**Comment by azymohliad** [comment]
Hi, so I'm planning to change "WatchMate" to "Watchmate" wherever it is visible to the user (#43) for the next release. But preserve the app ID as `io.gitlab.azymohliad.WatchMate` for now.

**Comment by azymohliad** [comment]
Hey, so [v0.5.0](https://github.com/azymohliad/watchmate/releases/tag/v0.5.0) is out. It should be up on Flathub in a few hours and hopefully soon in community distro packages. Among other things it fixes the name for the HIG compliance as "Watchmate". I'll close the issue now. If the renaming topic comes up again, I'll make sure to link this issue in the future discussions.
