### ISSUE TITLE
Run in the background

### ISSUE THREAD

**Issue by PhilDevProg** [azymohliad/watchmate#37]
At the moment I have to keep the app open all the time. It would be great if the app could run in the background.

**Comment by azymohliad** [comment]
Yep, I completely agree. Thanks for filing an issue. I'll try to look into it soon

**Comment by TheKrafter** [comment]
This would be great!

**Comment by TheKrafter** [comment]
How easy would it be to make just the UI close (with the rest of the app still running) on window destroy, and when the app is launched it simply reopens the UI?

I would love to contrib but am unfortunately not very familiar with rust (yet)

**Comment by azymohliad** [comment]
I don't know yet how easy is that, never done it before. But I've resumed the work on the app today, and planned to implement background service tomorrow. Sorry for being inactive on it for so long.

Today I've added automatic reconnection and persistent settings (#41), which I think are both needed for proper background service implementation. Besides just keeping running in background after closing the window, I also want to implement proper GNOME background app indicator before releasing it

**Comment by azymohliad** [comment]
> I would love to contrib but am unfortunately not very familiar with rust (yet)

The contributions are most welcome! Though I genuinely don't know if this is a good first issue to learn the code base from. I will know more tomorrow, but I'd also try to implement it while I have momentum.

In general if you're interested to dive deeper into the code, I'm happy to answer any questions that I can (I could enable github discussions if this isn't the best place, or matrix/telegram/discord also work for me).

**Comment by azymohliad** [comment]
A little update. Running in background should be pretty easy with GTK in theory, but Watchmate doesn't use GTK directly, but a functional-style wrapper [Relm4](https://relm4.org/) on top. And it turns out, it's not currently supported there. The good news is that it shouldn't be very hard to implement the support, and I'll try to help and lead the effort.
 
 To give a bit more details, I've found two options to close the GUI and keep the app running:
 1. Simply hide the main window e.g. using [Gtk.Window.set_hide_on_close](https://docs.gtk.org/gtk4/method.Window.set_hide_on_close.html)
 2. Destroy the GUI on close, but keep the app running anyway using [Gio.Application.hold](https://docs.gtk.org/gio/method.Application.hold.html). I assume the main point here is to release some memory while in background.
 
Additionally, sandboxed apps need to request a permission to run in background from [org.freedesktop.portal.Background](https://flatpak.github.io/xdg-desktop-portal/docs/#gdbus-org.freedesktop.portal.Background). All that is easily doable with Relm4.

But to switch back to foreground, it should handle the [Gio.Application::activate](https://docs.gtk.org/gio/signal.Application.activate.html) signal, and restore the GUI there (set the main window visible or reinitialize it depending on the options above). But this signal is used by Relm4 internally for the initial setup, so currently can't be reused for anything else.

**Comment by azymohliad** [comment]
So the Relm4 patch is accepted and a simple background mode is merged now. GNOME 44 background app indicator works automagically. Now I need to add a main menu to have an explicit quit option.

**Comment by azymohliad** [comment]
Hey, so [v0.5.0](https://github.com/azymohliad/watchmate/releases/tag/v0.5.0) is out, bringing a whole bunch of features necessary for a good background mode experience. It should be up on Flathub in a few hours and hopefully soon in community distro packages. I'll close the issue now. If it doesn't work for you folks, I'd appreciate a bug report :)
